language: go
arch:
  - amd64
  - ppc64le

go:
  - 1.3
  - 1.4
  - 1.5
jobs:
 exclude:
 exclude: # Excluding below jobs as "go" versions earlier than 1.5 are not supported for arch: ppc64le
  - arch: ppc64le
    go: 1.3
  - arch: ppc64le
    go: 1.4
    
sudo: false
